# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

permissions:
  contents: read

jobs:
  build:
    name: ${{ matrix.os }} / Java 21
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: gradle
      - name: make gradle wrapper executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      - name: build on Linux
        if: runner.os != 'Windows'
        run: ./gradlew build
      - name: build on Windows
        if: runner.os == 'Windows'
        run: .\gradlew.bat build
      - name: capture build artifacts
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v7
        with:
          name: observercam-${{ github.sha }}
          path: |
            build/libs/observercam-*.jar
            !build/libs/observercam-*-sources.jar
          retention-days: 14
